export const ORDER_CREAT_REQUEST = "ORDER_CREAT_REQUEST";
export const ORDER_CREAT_SUCCESS = "ORDER_CREAT_SUCCESS";
export const ORDER_CREAT_FAIL = "ORDER_CREAT_FAIL";
export const ORDER_CREAT_RESET = "ORDER_CREAT_RESET";
