export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREAT_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREAT_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREAT_RESET";
